# Generated by Django 3.2.7 on 2021-09-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accruals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='accruals.payment'),
        ),
    ]
