# Generated by Django 3.2.7 on 2021-09-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accruals', '0002_alter_accrual_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
