# Generated by Django 3.2.7 on 2022-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accruals', '0007_auto_20220322_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_title',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
